# Generated by Django 2.0.3 on 2019-09-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinenerplatters_pasta_salad_subs_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DinenerPlatters',
            new_name='DinnerPlatters',
        ),
    ]
