# Generated by Django 2.0.3 on 2019-09-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190919_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logeado',
            field=models.BooleanField(default=False),
        ),
    ]
