# Generated by Django 2.0.3 on 2019-11-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_client_logeado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('userID', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=64)),
                ('userID', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='order_product',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
        ),
    ]
