# Generated by Django 2.0.3 on 2019-11-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191123_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=64)),
                ('productID', models.CharField(max_length=64)),
                ('topings', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=64)),
                ('tipe', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='quantity',
        ),
        migrations.AddField(
            model_name='carrito',
            name='topings',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='product',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='topping',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Order_product',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
