# Generated by Django 2.0.3 on 2019-11-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191124_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
